{% set tpl = ix_lib.base.render.Render(values) %}

{% set app = tpl.add_container(values.consts.app_container_name, "image") %}
{# Create permissions container #}
{% set perms = tpl.deps.perms("perms_container_name") %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{% do app.add_caps(["SETUID", "SETGID", "CHOWN", "FOWNER", "DAC_OVERRIDE"]) %}
{% do app.healthcheck.set_test("curl", {"port": values.consts.internal_web_port, "path": "/"}) %}

{% do app.environment.add_user_envs(values.movienight.additional_envs) %}

{% if not values.network.host_network %}
  {% do app.add_port(values.network.web_port, {"container_port": values.consts.internal_http_port}) %}
  {% do app.add_port(values.network.https_port, {"container_port": values.consts.internal_thhp_port}) %}
  {% do app.add_port(values.network.rtmp_port, {"container_port": values.consts.internal_rtmp_port}) %}
{% endif %}

{# Add permission actions #}
{% do perms.add_or_skip_action("config", values.storage.data, perms_config) %}
{% do app.add_storage(values.consts.internal_data_path, values.storage.data) %}

{% do tpl.portals.add(values.network.web_port) %}
{% do tpl.notes.set_body(values.consts.notes_body) %}

{% do tpl.notes.add_info("After first setup please visiting https://github.com/zorglube/MovieNight/blob/master/readme.md") %}

{{ tpl.render() | tojson }}
