annotations:
  min_scale_version: 24.10.2.2
app_version: 1.0.0
capabilities: []
categories:
- media
changelog_url: https://github.com/zorglube/MovieNight
date_added: '2026-07-30'
description: single-instance streaming server with chat
home: https://github.com/zorglube/MovieNight
host_mounts: []
icon: https://media.sys.truenas.net/apps/movienight/icons/movienight.png
keywords:
- media
- streaming
lib_version: 2.1.65
lib_version_hash:
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com
name: movienight
run_as_context:
- description: MovieNight runs asany non-root user.
  gid: 568
  group_name: movienight
  uid: 568
  user_name: movienight
screenshots: []
sources:
- https://github.com/zorglube/MovieNight
title: MovieNight
train: community
version: 1.2.23
