images:
  image:
    repository: ruepp/movienight
    tag: latest
consts:
  app_container_name: movienight
  internal_data_path: /data
  internal_http_port: 8089
  internal_rtmp_port: 1935
  notes_body: |
    ## See the documentation on GitHub
    
    By default:
        - Port 8089 expose the MovieNight web interface.
        - Port 1935 listen to an RTMP stream, from OBS for example.
        - Settings should be mapped from /data, like /data/config/settings.json for settings.json, /data/static for static contents, /data/emotes for the emotes.
